HairdresserSalon/Controllers/HairdresserController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HairdresserSalon.Models;
using HairdresserSalon.Repositories.Abstract;
using Convey.CQRS.Commands;
using Convey.CQRS.Queries;
using HairdresserSalon.Commands.Hairdresser;
using HairdresserSalon.Queries.Hairdresser;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using HairdresserSalon.Queries.User;
using HairdresserSalon.Areas.Identity.Data;

namespace HairdresserSalon.Controllers
{
    [Authorize]
    public class HairdresserController : Controller
    {
        private readonly ICommandDispatcher _commandDispatcher;
        private readonly IQueryDispatcher _queryDispatcher;
        public HairdresserController(ICommandDispatcher commandDispatcher, IQueryDispatcher queryDispatcher)
        {
            _commandDispatcher = commandDispatcher;
            _queryDispatcher = queryDispatcher;

        }

        //GET get all hairdressers
        public ActionResult Index()
        {
            Guid userId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            AppUser appUser = _queryDispatcher.QueryAsync(new GetUserById { Id = userId }).Result;
            if (appUser.Employee == true)
            {
                var list = _queryDispatcher.QueryAsync(new GetAllHairdressers()).Result;
                return View(list);
            }
            return View("Areas/Identity/Pages/Account/AccessDenied.cshtml");
            
        }

        //GET create Hairdresser
        public ActionResult Create()
        {
            Guid userId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            AppUser appUser = _queryDispatcher.QueryAsync(new GetUserById { Id = userId }).Result;
            if (appUser.Admin == true)
            {
                return View(new HairdresserModel());
            }                
            return View("Areas/Identity/Pages/Account/AccessDenied.cshtml");
        }

        //POST create Hairdresser
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HairdresserModel hairdresser)
        {
            Guid userId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            AppUser appUser = _queryDispatcher.QueryAsync(new GetUserById { Id = userId }).Result;
            if (appUser.Admin == true)
            {
                if (ModelState.IsValid)
                {
                    _commandDispatcher.SendAsync(new CreateHairdresser(hairdresser.Name));
                    return RedirectToAction("Index");
                }
                return View("Create");
                //_hairdresserRepository.AddHairdresser(hairdresser);
            }
            return View("Areas/Identity/Pages/Account/AccessDenied.cshtml");
        }

        public ActionResult Delete(Guid id)
        {
            Guid userId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            AppUser appUser = _queryDispatcher.QueryAsync(new GetUserById { Id = userId }).Result;
            if (appUser.Admin == true)
            {
                return View(_queryDispatcher.QueryAsync(new GetHairdresser { Id = id }).Result);
            }
            return View("Areas/Identity/Pages/Account/AccessDenied.cshtml");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Guid id, HairdresserModel hairdresser)
        {
            Guid userId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            AppUser appUser = _queryDispatcher.QueryAsync(new GetUserById { Id = userId }).Result;
            if (appUser.Admin == true)
            {
                _commandDispatcher.SendAsync(new DeleteHairdresser(id));
                return RedirectToAction("Index");
            }
            return View("Areas/Identity/Pages/Account/AccessDenied.cshtml");
        }
    }
}

HairdresserSalon/Controllers/HourController.cs
using Convey.CQRS.Commands;
using Convey.CQRS.Queries;
using HairdresserSalon.Commands.Hour;
using HairdresserSalon.Queries.Day;
using HairdresserSalon.Queries.Hour;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HairdresserSalon.Controllers
{
    public class HourController : Controller
    {
        private readonly IQueryDispatcher _queryDispatcher;
        private readonly ICommandDispatcher _commandDispatcher;
        public HourController(IQueryDispatcher queryDispatcher, ICommandDispatcher commandDispatcher)
        {
            _queryDispatcher = queryDispatcher;
            _commandDispatcher = commandDispatcher;
        }
        public ActionResult Edit(Guid id)
        {
            TempData["day"] = id;
            var day = _queryDispatcher.QueryAsync(new GetDay { Id = id }).Result;
            //var list = _queryDispatcher.QueryAsync(new GetHoursForDay { Id = id }).Result;
            return View(day);
        }

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Delete(Guid id)
        {
            Guid dayId = (Guid)TempData["day"];
            _commandDispatcher.SendAsync(new Delete(id));
            return RedirectToAction("Edit", new { id = dayId });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DateTime hour)
        {
            Guid dayId = (Guid)TempData["day"];
            var list = _queryDispatcher.QueryAsync(new GetHoursForDay { Id = dayId }).Result;
            bool check = false;
            foreach (var item in list)
            {
                if (item.Hour.Hour == hour.Hour && item.Hour.Minute == hour.Minute)
                {
                    check = true;
                    TempData["Error"] = "Wybrana godzina już istnieje.";
                }
            }

            if (check==false)
            {
                _commandDispatcher.SendAsync(new AddHour(dayId, hour));
                TempData["Success"] = "Dodano godzinę.";
            }
            

            return RedirectToAction("Edit", new { id = dayId });
        }
    }
}

HairdresserSalon/Controllers/TimeTableController.cs
using Convey.CQRS.Commands;
using Convey.CQRS.Queries;
using HairdresserSalon.Commands.Day;
using HairdresserSalon.Models;
using HairdresserSalon.Queries.Day;
using HairdresserSalon.Repositories.Abstract;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HairdresserSalon.Controllers
{
    public class TimeTableController : Controller
    {
        private readonly IQueryDispatcher _queryDispatcher;
        private readonly ICommandDispatcher _commandDispatcher;
        public TimeTableController(IQueryDispatcher queryDispatcher, ICommandDispatcher commandDispatcher)
        {
            _queryDispatcher = queryDispatcher;
            _commandDispatcher = commandDispatcher;
        }

        public ActionResult Index(Guid id, int pageNumber=2)
        {
            TempData["id"] = id;
            var list = _queryDispatcher.QueryAsync(new GetAllDaysForHairdresser { Id = id }).Result;
            list = list.Where(x => x.Date >= DateTime.Today.AddDays(-7)).ToList();
            //return View(list);
            return View(PaginatedList<DayModel>.CreateAsync(list, pageNumber, 6));
        }

        public ActionResult Create()
        {
            return View(new DayModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DateTime datefield)
        {
            Guid id;
            var a = Guid.TryParse(TempData["id"].ToString(), out id);

            bool correct = true;
            var list = _queryDispatcher.QueryAsync(new GetAllDaysForHairdresser { Id = id }).Result;
            foreach (var item in list)
            {
                if (item.Date ==datefield)
                {
                    correct = false;
                    TempData["Error"] = "Ten dzień został już dodany.";
                    break;
                    
                }
            }
            if (datefield.DayOfWeek==DayOfWeek.Sunday)
            {
                correct = false;
                TempData["Error"] = "Nie dodano dnia, ponieważ wybrany dzień to niedziela.";
            }

            if (correct == true)
            {
                _commandDispatcher.SendAsync(new CreateDay(datefield, id));
                TempData["Success"] = "Dodano dzień.";
            }
            
            return RedirectToAction("Index", new { id = TempData["id"] });
            


        }

        
    }
}

HairdresserSalon/Views/TimeTable/Index.cshtml
@model PaginatedList<DayModel>
@{
    ViewData["Title"] = "Harmonogram";
    Layout = "~/Views/Shared/_LayoutEmploee.cshtml";
}

<div id="PlaceHolder"></div>
@if (TempData["Success"] != null)
{
    <div class="row">
        <div class="col-lg">
            <div class="rounded pg-3 alert-success">
                @TempData["Success"].ToString()
            </div>
        </div>
    </div>
}
@if (TempData["Error"] != null)
{
    <div class="row">
        <div class="col-lg">
            <div class="rounded pg-3 alert-danger">
                @TempData["Error"].ToString()
            </div>
        </div>
    </div>
}
<h1 class="zajete">Harmonogram</h1>


<h3>Dodaj dzień</h3>
<div class="row">
    <div class="col-md-3">
        <form asp-action="Create">
            <div class="form-group">
                @*<label asp-for="Date"></label>*@
                @*@Html.TextBoxFor(Model => Model.Date, new { type = "date" })*@
                <input class="form-control" type="date" id="datefield" name="datefield" required>
            </div>  
            <div>
                <input class="btn btn-primary" type="submit" value="Dodaj" />
            </div>
        </form>
    </div>
</div>



<script>
    var today = new Date();
    var dd = today.getDate();
    var mm = today.getMonth() + 1; //January is 0!
    var yyyy = today.getFullYear();
    if (dd < 10) {
        dd = '0' + dd
    }
    if (mm < 10) {
        mm = '0' + mm
    }

    today = yyyy + '-' + mm + '-' + dd;
    document.getElementById("datefield").setAttribute("min", today);
</script>

<div style="margin: 10px 0px 10px 0px">
    <table class="table">

        @foreach (var day in Model)
        {

            <th class="table-light table-bordered">
                @Html.DisplayFor(modelItem => day.Date)
                @Html.ActionLink("Modyfikuj", "Edit", "Hour", new { id = day.Id })
            </th>

            <tr class="table-bordered">

                @foreach (var hour in day.Hours)
                {
                    @if (hour.Available == false)
                    {
                        <td style="background-color: #8c312a">
                            @Html.DisplayFor(modelItem => hour.Hour)
                        </td>

                    }
                    else
                    {
                        <td>
                            @Html.DisplayFor(modelItem => hour.Hour)
                        </td>
                    }
                }

            </tr>
        }

    </table>
</div>





    


    @{
        var prevDisabled = !Model.PreviousPage ? "disabled" : "";
        var nextDisabled = !Model.NextPage ? "disabled" : "";
    }
<center>
    <a asp-action="Index"
       asp-route-pageNumber="@(Model.PageIndex - 1)"
       class="btn btn-default bg-light @prevDisabled">
        Poprzednia
    </a>
    <a asp-action="Index"
       asp-route-pageNumber="@(Model.PageIndex + 1)"
       class="btn btn-default bg-light @nextDisabled">
        Następna
    </a>
</center>

<a class="btn btn-primary" asp-controller="Hairdresser" asp-action="Index">Powrót</a>