HairdresserSalon/Controllers/DayController.cs
using Convey.CQRS.Queries;
using HairdresserSalon.Models;
using HairdresserSalon.Queries.Day;
using HairdresserSalon.Repositories.Abstract;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HairdresserSalon.Controllers
{
    public class DayController : Controller
    {
        private readonly IQueryDispatcher _queryDispatcher;
        public DayController(IQueryDispatcher queryDispatcher)
        {
            _queryDispatcher = queryDispatcher;
        }

        public IActionResult Index(int pageNumber = 1)
        {
            var list = _queryDispatcher.QueryAsync(new GetAllAvailableDates()).Result;
            return View(PaginatedList<DayModel>.CreateAsync(list, pageNumber, 6));
        }

        public IActionResult IndexEmp(int pageNumber = 1)
        {
            TempData["emp"] = true;
            var list = _queryDispatcher.QueryAsync(new GetAllAvailableDates()).Result;
            return View("Index",PaginatedList<DayModel>.CreateAsync(list, pageNumber, 6));
        }

        public IActionResult Details()
        {
            
            return View();
        }

    }
}

HairdresserSalon/Controllers/OpinionController.cs
using HairdresserSalon.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Convey.CQRS.Queries;
using HairdresserSalon.Queries.Opinion;

namespace HairdresserSalon.Controllers
{
    public class OpinionController : Controller
    {
        private readonly IQueryDispatcher _queryDispatcher;
        public OpinionController(IQueryDispatcher queryDispatcher)
        {
            _queryDispatcher = queryDispatcher;
        }
        public IActionResult Index(int pageNumber = 1)
        {
            var list = _queryDispatcher.QueryAsync(new GetAllOpinions()).Result;
            float suma = 0;
            foreach (var item in list)
            {
                suma += item.Opinion.Rating;
            }
            float srednia = suma / list.Count();
            TempData["srednia"] = srednia;
            return View(PaginatedList<VisitModel>.CreateAsync(list, pageNumber, 5));
        }

        

        
    }
}

HairdresserSalon/Controllers/UserController.cs
using Convey.CQRS.Commands;
using Convey.CQRS.Queries;
using HairdresserSalon.Areas.Identity.Data;
using HairdresserSalon.Commands.User;
using HairdresserSalon.Queries.User;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace HairdresserSalon.Controllers
{
    public class UserController : Controller
    {
        private readonly IQueryDispatcher _queryDispatcher;
        private readonly ICommandDispatcher _commandDispatcher;
        public UserController(IQueryDispatcher queryDispatcher, ICommandDispatcher commandDispatcher)
        {
            _queryDispatcher = queryDispatcher;
            _commandDispatcher = commandDispatcher;
        }
        public IActionResult Index()
        {
            Guid userId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            AppUser appUser = _queryDispatcher.QueryAsync(new GetUserById { Id = userId }).Result;
            if (appUser.Admin == true)
            {
                var list = _queryDispatcher.QueryAsync(new GetEmployees()).Result;
                return View(list);
            }
            return View("Areas/Identity/Pages/Account/AccessDenied.cshtml");
        }

        public IActionResult AddEmployee(string email)
        {
            Guid userId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            AppUser appUser = _queryDispatcher.QueryAsync(new GetUserById { Id = userId }).Result;
            if (appUser.Admin == true)
            {
                var list = _queryDispatcher.QueryAsync(new GetUsers()).Result;
                //bool exist = false;
                AppUser _appUser = new AppUser();

                foreach (AppUser user in list)
                {
                    if (user.Email == email)
                    {
                        //exist = true;
                        _appUser = user;
                        if (user.Employee == true)
                        {
                            TempData["Error"] = "Konto zostało już dodane";
                            return RedirectToAction("Index");
                        }
                        break;
                    }
                    TempData["Error"] = "Nie znaleziono takiego konta";
                }


                //if (exist==true)
                //{
                _commandDispatcher.SendAsync(new AddEmployee(_appUser));
                
                //}
                return RedirectToAction("Index");
            }
            return View("Areas/Identity/Pages/Account/AccessDenied.cshtml");
        }

        public IActionResult DeleteEmployee(Guid id)
        {
            Guid userId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            AppUser appUser = _queryDispatcher.QueryAsync(new GetUserById { Id = userId }).Result;
            if (appUser.Admin == true)
            {
                _commandDispatcher.SendAsync(new DeleteEmployee(id));
                return RedirectToAction("Index");
            }
            return View("Areas/Identity/Pages/Account/AccessDenied.cshtml");
        }
        
        public IActionResult ChangeAdminStatus(Guid id)
        {
            Guid userId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            AppUser appUser = _queryDispatcher.QueryAsync(new GetUserById { Id = userId }).Result;
            if (appUser.Admin == true)
            {
                _commandDispatcher.SendAsync(new ChangeAdminStatus(id));
                return RedirectToAction("Index");
            }
            return View("Areas/Identity/Pages/Account/AccessDenied.cshtml");
        }
    }
}

HairdresserSalon/Controllers/VisitController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Convey.CQRS.Queries;
using HairdresserSalon.Queries.Hour;
using HairdresserSalon.Queries.Day;
using HairdresserSalon.Queries.Service;
using System.Security.Claims;
using HairdresserSalon.Models;
using HairdresserSalon.Queries.Customer;
using Microsoft.AspNetCore.Mvc.Rendering;
using Convey.CQRS.Commands;
using HairdresserSalon.Commands.Visit;
using Microsoft.AspNetCore.Authorization;
using HairdresserSalon.Queries.Visit;
using HairdresserSalon.Commands.Visit.Handlers;
using HairdresserSalon.Areas.Identity.Data;
using HairdresserSalon.Queries.User;
using HairdresserSalon.Commands.Customer;

namespace HairdresserSalon.Controllers
{
    [Authorize]
    public class VisitController : Controller
    {
        private readonly IQueryDispatcher _queryDispatcher;
        private readonly ICommandDispatcher _commandDispatcher;
        public VisitController(IQueryDispatcher queryDispatcher, ICommandDispatcher commandDispatcher)
        {
            _queryDispatcher = queryDispatcher;
            _commandDispatcher = commandDispatcher;
        }
        public IActionResult Index(string search, string id)
        {
            Guid userId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            AppUser appUser = _queryDispatcher.QueryAsync(new GetUserById { Id = userId }).Result;
            if (appUser.Employee == true)
            {
                var list = _queryDispatcher.QueryAsync(new GetAllVisits()).Result;
                if (search!=null)
                {
                    list = list.Where(x => x.Customer.LastName.ToLower() == search.ToLower()).ToList();
                }
                else if (id=="t")
                {
                    list = list.Where(x => x.Date.Day.Date == DateTime.Now).ToList();
                }
                return View(list);
            }
            return View("Areas/Identity/Pages/Account/AccessDenied.cshtml");

        }

        public IActionResult CustomerIndex()
        {
            Guid userId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var list = _queryDispatcher.QueryAsync(new GetVisitsForCustomer { Id = userId}).Result;
            return View(list);
        }

        public IActionResult VisitsHistory()
        {
            Guid userId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var list = _queryDispatcher.QueryAsync(new GetVisitsHistory { Id = userId }).Result;
            return View(list);
        }

        public IActionResult VisitsArchive(int id)
        {
            var list = _queryDispatcher.QueryAsync(new GetVisitsArchive()).Result;
            //if (id == 1)
            //{
            //    return View(list);
            //}
            if (id == 2)
            {
                list = list.Where(x => x.Ended == true);
                //return View(list);
            }
            if (id == 3)
            {
                list = list.Where(x => x.Canceled == true);
                //return View(list);
            }
            return View(list);
        }
        

        public IActionResult Create(Guid id)
        {
            var result = _queryDispatcher.QueryAsync(new GetHour { Id = id }).Result;
            var result2 = _queryDispatcher.QueryAsync(new GetDayAndHairdresser { Id = result.Day.Id }).Result;
            var services = _queryDispatcher.QueryAsync(new GetAllServices()).Result;
            ViewBag.Services = new SelectList(services, "Id", "Name");
            
            VisitModel visit = VisitModel.Create(Guid.NewGuid(), result2.Hairdresser, false, result, false);
            TempData["hairdresser"] = visit.Hairdresser.Id.ToString();
            TempData["date"] = visit.Date.Id.ToString();

            //bool emp=false;
            //if (TempData.ContainsKey("emp"))
            //    emp = (bool)TempData["emp"];

            //if (emp==true)
            //{
            //    return View(visit);
            //}

            return View(visit);


        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(VisitModel visit)
        {        
            Guid hairdresserId = (Guid)TempData["hairdresser"];
            Guid dateId = (Guid)TempData["date"];
            Guid serviceId = Guid.Parse(Request.Form["Services"]);
            Guid userId = Guid.Empty;
            if (visit.Customer==null)
            {
                try
                {
                    userId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
                }
                catch (Exception ex)
                {
                    return NotFound();
                }
            }
            else
            {
                if (ModelState.IsValid)
                {
                    bool customerExist = false;
                    CustomerModel _customer = new CustomerModel();
                    var customers = _queryDispatcher.QueryAsync(new GetAllCustomers()).Result;
                    foreach (var item in customers)
                    {
                        if (item.FirstName == visit.Customer.FirstName && item.LastName == visit.Customer.LastName)
                        {
                            customerExist = true;
                            _customer = item;

                        }
                    }

                    if (customerExist == false)
                    {
                        CustomerModel customer = CustomerModel.Create(Guid.NewGuid(), visit.Customer.FirstName, visit.Customer.LastName, visit.Customer.Email, visit.Customer.PhoneNumber);
                        _commandDispatcher.SendAsync(new CreateCustomer(customer));
                        userId = customer.Id;
                    }
                    else
                    {
                        userId = _customer.Id;
                    }
                }
                else
                {
                    TempData["emp"] = true;
                    TempData["error"] = "Uzupełnij dane";
                    return RedirectToAction("Create", new { id = visit.Id });
                }
                
                
                
                
            }
            
            
            _commandDispatcher.SendAsync(new CreateVisit(serviceId, userId, hairdresserId, dateId, visit));
            var b = Test.a;
            if (b==true)
            {
                return RedirectToAction("CustomerIndex");
            }
            TempData["Error"] = "Nie umówiono wizyty. Niewystarczający czas na wykonanie usługi. Proszę wybrać inny termin.";
            return RedirectToAction("Index", "Day");

        }

        public ActionResult VisitNotCreated()
        {
            return View();
        }

        public ActionResult Details(Guid id)
        {
            Guid userId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            AppUser appUser = _queryDispatcher.QueryAsync(new GetUserById { Id = userId }).Result;
            if (appUser.Employee == true)
            {
                var visit = _queryDispatcher.QueryAsync(new GetVisitDetails { Id = id }).Result;
                if (visit.Customer.VisitsCounter % 10 == 0)
                {
                    visit.Price = visit.Price - visit.Price * 20 / 100;
                }
                return View(visit);
            }
            return View("Areas/Identity/Pages/Account/AccessDenied.cshtml");
        }

        public ActionResult DetailsCustomer(Guid id)
        {
            var visit = _queryDispatcher.QueryAsync(new GetVisitDetails { Id = id }).Result;
            return View(visit);
        }

        //GET edit
        public ActionResult CancelVisit(Guid id)
        {
            var visit = _queryDispatcher.QueryAsync(new GetVisitDetails { Id = id }).Result;
            return View(visit);
        }

        //POST edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CancelVisit(Guid id, ServiceModel serviceModel)
        {
            // 1 klient
            // 2 zakład
            int source = int.Parse(TempData["source"].ToString());
            _commandDispatcher.SendAsync(new CancelVisit(id, source));
            if (source == 2)
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("CustomerIndex");
        }

        
        
        //GET edit
        public ActionResult EndVisit(Guid id)
        {
            Guid userId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            AppUser appUser = _queryDispatcher.QueryAsync(new GetUserById { Id = userId }).Result;
            if (appUser.Employee == true)
            {
                var visit = _queryDispatcher.QueryAsync(new GetVisitDetails { Id = id }).Result;
                return View(visit);
            }
            return View("Areas/Identity/Pages/Account/AccessDenied.cshtml");
        }

        
        
        //POST edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EndVisit(Guid id, ServiceModel serviceModel)
        {
            Guid userId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            AppUser appUser = _queryDispatcher.QueryAsync(new GetUserById { Id = userId }).Result;
            if (appUser.Employee == true)
            {
                _commandDispatcher.SendAsync(new EndVisit(id));
                return RedirectToAction("Index");
            }
            return View("Areas/Identity/Pages/Account/AccessDenied.cshtml");
        }

        public ActionResult AddOpinion(Guid id)
        {
            TempData["id"] = id;
            var visit = _queryDispatcher.QueryAsync(new GetVisitDetails { Id = id }).Result;
            return View(visit);
        }

        //POST
        [HttpPost]

HairdresserSalon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HairdresserSalon</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HairdresserSalon</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Day" asp-action="Index">Umów wizytę</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Service" asp-action="PriceList">Cennik</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Opinion" asp-action="Index">Opinie</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Information" asp-action="Index">Kontakt</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Visit" asp-action="Index">Panel pracownika</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - HairdresserSalon
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HairdresserSalon/Views/Shared/_LayoutEmploee.cshtml
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HairdresserSalon</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HairdresserSalon</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Visit" asp-action="Index">Wizyty</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Day" asp-action="IndexEmp">Umów wizytę</a>                            
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Visit" asp-action="VisitsArchive">Archiwum wizyt</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hairdresser" asp-action="Index">Fryzjerzy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Service" asp-action="Index">Usługi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Uprawnienia</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Information" asp-action="Edit">Informacje</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - HairdresserSalon
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>